# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0004_auto_20160716_1259'),
        ('website', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ostinato_pages.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ostinato_pages.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=b'uploads/'),
        ),
    ]
