# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160716_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
        migrations.RemoveField(
            model_name='video',
            name='page',
        ),
    ]
