language: python
python:
    - 2.7

install:
    - pip install --upgrade setuptools
    - python demoproject/bootstrap.py -c demoproject/travis.cfg
    - demoproject/bin/buildout -c demoproject/travis.cfg

script:
    - demoproject/bin/test