version: '2'

services:
  demo:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./demo/:/demo/
      - ./ostinato/:/demo/ostinato/
    ports:
      - "8000:8000"

