# Generated by Django 2.1.5 on 2019-01-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ostinato_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A unique, url-friendly slug based on the title', unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('state', models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='private', max_length=20, verbose_name='State')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish date')),
                ('archived_date', models.DateTimeField(blank=True, null=True, verbose_name='Archived date')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow comments')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('cache_page', models.BooleanField(default=False)),
                ('max_latest_entries', models.IntegerField(default=10, help_text='The maximum number of latest entries to display')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_landingpage_content', to='ostinato_pages.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
