# Generated by Django 2.1.5 on 2019-01-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='show_in_nav',
        ),
    ]
