# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 21:11
from __future__ import unicode_literals

from django.db import migrations


def update_states(apps, schema_editor):
    """
    Update from old integer based states to the now more verbose
    states
    """
    Page = apps.get_model('ostinato_pages', 'Page')
    for page in Page.objects.all():
        if page.state == '1':
            page.state == 'private'
        elif page.state == '5':
            page.state == 'public'
        page.save()



class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0002_auto_20160420_2100'),
    ]

    operations = [
        migrations.RunPython(update_states),
    ]

