# Generated by Django 2.1.5 on 2019-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0002_remove_page_show_in_nav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (('private_view_page', '[Private] Can View Page'), ('private_edit_page', '[Private] Can Edit Page'), ('private_delete_page', '[Private] Can Delete Page'), ('can_publish_page', 'Can Make public Page'), ('public_view_page', '[Public] Can View Page'), ('public_edit_page', '[Public] Can Edit Page'), ('public_delete_page', '[Public] Can Delete Page'), ('can_retract_page', 'Can Make private Page')), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20, verbose_name='State'),
        ),
    ]
