# Generated by Django 2.1.5 on 2019-10-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0003_auto_20191001_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='redirect',
        ),
    ]
