# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato_pages', '0003_auto_20160420_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='state',
            field=models.CharField(choices=[(b'public', b'Public'), (b'private', b'Private')], default=b'public', max_length=20, verbose_name='State'),
        ),
    ]
