"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def basedir(*path):
    return os.path.join(BASE_DIR, *path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zs$5^s-m3i3(kjt8#mj1384%j+tv+htgg(o-nmcou-%!kxyvxo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE = {
    'host': 'localhost',
    'name': 'Ostinato Demo',
}

# Application definition

INSTALLED_APPS = [
    'ostinato.admin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'website',

    'ostinato.pages',
    'ostinato.contentfilters',
    'ostinato.medialib',

    'mptt',
    'taggit',

    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/src/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'


# Send emails to the console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Ostinato settings
OSTINATO_PAGES = {
    'default_state': 'private',

    'templates': {
        'website.homepage': {
            'label': 'Home Page',
            'admin_form': 'website.forms.HomePageForm',
            'template': 'pages/home_page.html',
            'page_inlines': [
                'website.forms.ImageInline',
                'website.forms.VideoInline'
            ],
        },

        'website.genericpage': {
            'label': 'Generic Page',
            'template': 'pages/generic_page.html',
            'admin_form': 'website.forms.GenericPageForm'
        },

        'website.toplevellistpage': {
            'label': 'Top Level List',
            'template': 'pages/top_level_list_page.html',
            'view': 'website.views.TopLevelListPageView'
        },

        'website.casestudypage': {
            'label': 'Case Study',
            'template': 'pages/case_study_page.html',
            'admin_form': 'website.forms.GenericPageForm',
        },

        'website.contactpage': {
            'label': 'Contact Page',
            'template': 'pages/contact_page.html',
            'admin_form': 'website.forms.ContactPageForm',
            'view': 'website.views.ContactPageView',
        },

        'blog.landingpage': {
            'label': 'Blog Landing Page',
            'template': 'blog/landing_page.html',
            'view': 'blog.views.LandingPageView',
        },
    },
}

OSTINATO_CONTENTBROWSER = {
    'browsers': [
        'website.views.PageSummary',
        'website.views.EntrySummary',
        'website.views.VideoBrowser',
        'website.views.ImageBrowser',
    ],
}


# Third party app config
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'plugins': "paste",
    'relative_urls': False,
    # 'remove_script_host': False,
    # 'document_base_url': '',
    'content_css': "%scss/tinymce_content.css" % STATIC_URL,

    'theme_advanced_buttons1' : "bold,italic,|,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,|,undo,redo,|,link,unlink,code,image,|,formatselect,|,pastetext,",
    'theme_advanced_buttons2' : "",
    'theme_advanced_buttons3' : "",
    'theme_advanced_buttons4' : "",
    'theme_advanced_toolbar_location' : "top",
    'theme_advanced_toolbar_align' : "left",
    'theme_advanced_statusbar_location' : "bottom",
    'theme_advanced_resizing' : True,
    'theme_advanced_blockformats' : "h1,h2,h3,p,blockquote",

    'width': 760,
    'height': 400,

    'paste_strip_class_attributes': 'all',
    'paste_auto_cleanup_on_paste' : True,
    'paste_convert_middot_lists': False,
    'paste_remove_styles' : True,
    'paste_retain_style_properties': '',

    'extended_valid_elements': "a[class|name|href|target|title|onclick|rel],"\
        "script[type|src],"\
        "iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],"\
        "$elements",
}
