# Generated by Django 2.1.5 on 2019-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text="Absolute path for old URL, excluding the domain name. Example: '/events/search/'.", max_length=250)),
                ('new_path', models.CharField(blank=True, help_text="This can be either an absolute path (as above) or a full URL starting with 'http://'.", max_length=250)),
                ('code', models.PositiveSmallIntegerField(choices=[(302, 'Moved Temporarily'), (301, 'Moved Permanently'), (410, 'Gone')], default=302)),
            ],
        ),
    ]
